---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(sf)
library(tidyverse)
library(raster)
```

Set projections

```{r projections}
# ESRI projection for mapping. 
# https://spatialreference.org/ref/esri/europe-albers-equal-area-conic/ for reference
crs1 <- 102013
crs2 <- 4326
```


```{r boston-download}
url_boundary <- "http://bostonopendata-boston.opendata.arcgis.com/datasets/142500a77e2a4dbeb94a86f7e0b568bc_9.zip"
url_streets <- "http://bostonopendata-boston.opendata.arcgis.com/datasets/cfd1740c2e4b49389f47a9ce2dd236cc_8.zip"
url_water <- "http://bostonopendata-boston.opendata.arcgis.com/datasets/2b3c0fa13b1c468eb702a3645fcc6bcb_5.zip"

curl::curl_download(url_boundary, destfile = "../data/boston_boundary.shp.zip")
curl::curl_download(url_streets, destfile = "../data/boston_streets.shp.zip")
curl::curl_download(url_water, destfile = "../data/boston_water.shp.zip")

unzip("../data/boston_boundary.shp.zip", exdir = "../data")
unzip("../data/boston_streets.shp.zip", exdir = "../data")
unzip("../data/boston_water.shp.zip", exdir = "../data")
```

```{r cambridge-download}
url_cambridge_streets <- "http://gis.cambridgema.gov/download/shp/TRANS_Centerlines.shp.zip"

curl::curl_download(url_cambridge_streets, destfile = "../data/cambridge_streets.shp.zip")

unzip("../data/cambridge_streets.shp.zip", exdir = "../data")
```



```{r load-shapefiles}
df_boundary <- sf::read_sf("../data", "City_of_Boston_Boundary")
df_streets <- sf::read_sf("../data", "Boston_Street_Segments")
df_water <- sf::read_sf("../data", "Hydrography_Polygon")

df_cambridge_streets <- sf::read_sf("../data", "TRANS_Centerlines")
```

Street categorization: The Cambridge streets are helpfully sorted into major and minor roads by the `MajorRoad` column, which takes values from 0-2.

```{r}
df_cambridge_streets %>% 
  count(MajorRoad)
```

These are probably ordered from 0: minor to 2: major.

Let's use the speed limits on Boston roads to do a similar categorizing:

```{r}
df_streets %>% 
  ggplot(aes(SPEEDLIMIT)) +
  geom_histogram()
```

```{r}
df_streets_labeled <- 
  df_streets %>% 
  mutate(MajorRoad = if_else(SPEEDLIMIT >= 30, 0, 3))
```


```{r vis}
## Plot
ggplot() +
  geom_sf(
    data = df_water,
    color = "darkslateblue",
    fill = "#d1e9eb",
    size = 0.01,
    alpha = 1
  ) +
  ## Roads
  geom_sf(
    data = df_streets_labeled %>% mutate(MajorRoad = as.factor(MajorRoad)),
    aes(size = MajorRoad)
  ) +
  geom_sf(
    data = df_cambridge_streets %>% mutate(MajorRoad = as.factor(MajorRoad)),
    # aes(size = MajorRoad)
    size = 0.04
  ) +
  ## Tail
  scale_size_manual(
    values = c(`0` = 0.02, `1` = 0.02, `2` = 0.02, `3` = 0.05)
  ) +
  coord_sf(
    xlim = c(-71.1, -71.0),
    ylim = c(+42.3, +42.37)
  ) +
  theme_void() +
  # theme_minimal() +
  theme(
    panel.background = element_rect(
      fill = "white"
    ),
    
    legend.position = "none",
    plot.caption = element_text(
      color = "grey20", 
      size = 40, 
      hjust = .5, 
      face = "plain", 
      family = "Didot"
    )
  ) +
  labs(
    caption = "Boston"
  )
```

